"""add_google_oauth_support

Revision ID: 097c6344a1bb
Revises: c9cd18ed7de2
Create Date: 2026-03-03 18:53:30.442285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097c6344a1bb'
down_revision: Union[str, Sequence[str], None] = 'c9cd18ed7de2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_normalized_key'), table_name='merchant')
    op.create_index(op.f('ix_merchant_normalized_key'), 'merchant', ['normalized_key'], unique=True)
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'oauth_provider')
    op.drop_column('users', 'google_id')
    op.drop_index(op.f('ix_merchant_normalized_key'), table_name='merchant')
    op.create_index(op.f('ix_merchant_normalized_key'), 'merchant', ['normalized_key'], unique=False)
    # ### end Alembic commands ###
