"""add ingestion_type to expense

Revision ID: 1cccc3313acc
Revises: d5eba1c3488f
Create Date: 2026-02-25 18:43:28.947584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cccc3313acc'
down_revision: Union[str, Sequence[str], None] = 'd5eba1c3488f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('ingestion_type', sa.String(length=32), server_default='manual', nullable=False))
    op.alter_column('source', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_source_name'), 'source', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_name'), table_name='source')
    op.alter_column('source', 'name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('expense', 'ingestion_type')
    # ### end Alembic commands ###
