"""add merchant learning

Revision ID: 79b7fba0eaaa
Revises: e8f7d6c5b4a3
Create Date: 2026-02-26 10:40:19.578331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79b7fba0eaaa'
down_revision: Union[str, Sequence[str], None] = 'e8f7d6c5b4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_log_id'), table_name='ingestion_log')
    op.drop_index(op.f('ix_ingestion_log_input_type'), table_name='ingestion_log')
    op.drop_index(op.f('ix_ingestion_log_status'), table_name='ingestion_log')
    op.drop_index(op.f('ix_ingestion_log_user_id'), table_name='ingestion_log')
    op.drop_table('ingestion_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('input_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('parsed_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('parsed_merchant', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('parsed_category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('expense_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], name=op.f('ingestion_log_expense_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ingestion_log_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ingestion_log_pkey'))
    )
    op.create_index(op.f('ix_ingestion_log_user_id'), 'ingestion_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_ingestion_log_status'), 'ingestion_log', ['status'], unique=False)
    op.create_index(op.f('ix_ingestion_log_input_type'), 'ingestion_log', ['input_type'], unique=False)
    op.create_index(op.f('ix_ingestion_log_id'), 'ingestion_log', ['id'], unique=False)
    # ### end Alembic commands ###
