"""add_normalized_key_to_merchant

Revision ID: c9cd18ed7de2
Revises: 79b7fba0eaaa
Create Date: 2026-03-03 09:02:55.767938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9cd18ed7de2'
down_revision: Union[str, Sequence[str], None] = '79b7fba0eaaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('merchant', sa.Column('normalized_key', sa.Text(), nullable=True))

    op.execute("""
        UPDATE merchant
        SET normalized_key = UPPER(regexp_replace(name, '[^A-Za-z]', '', 'g'))
    """)

    op.alter_column('merchant', 'normalized_key', nullable=False)

    op.create_index(op.f('ix_merchant_normalized_key'),
                    'merchant',
                    ['normalized_key'],
                    unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_normalized_key'), table_name='merchant')
    op.drop_column('merchant', 'normalized_key')
    # ### end Alembic commands ###
